### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by alelordelo** [yukiny0811/easy-node-editor#15]
Hi, thanks for sharing this!

It seems this guys have figured out a pretty good UI for Node Graphs:
https://github.com/AudioKit/Flow

And you built a nice way to handle components and data flow.

So my suggestion is... 
Why not build on top of AudioKit Flow, and add your workflow for registering nodes and data flow?

cheers from Stockholm!

**Comment by yukiny0811** [comment]
Hi! @alelordelo, thanks for your suggestion.

However, the UI design of EasyNodeEditor is still in progress, and I am not thinking of building this system on top of other libraries.

I will update the UI design in a little while, so feel free to add some UI features you want in the issues!

best
